### ISSUE TITLE
Cant Join

### ISSUE THREAD

**Issue by Stevelolp** [Dislaik/zombieoutbreak#7]
Hey, so when i start the server your mod gives 3 errors: 

`[MySQL] [ERROR] [zombieoutbreak] An error happens for query "SELECT * FROM clothes : []": ER_BAD_DB_ERROR: Unknown database 'es_extended.crafting'`
`[MySQL] [ERROR] [zombieoutbreak] An error happens for query "SELECT * FROM items : []": ER_BAD_DB_ERROR: Unknown database 'es_extended.crafting'`
`[MySQL] [ERROR] [zombieoutbreak] An error happens for query "SELECT * FROM weapons : []": ER_BAD_DB_ERROR: Unknown database 'es_extended.crafting'`

after restarting it says:
`[zombieoutbreak] An error happens for query "SELECT * FROM clothes : []": ER_NO_SUCH_TABLE: Table 'es_extended.clothes' doesn't exist`
`[zombieoutbreak] An error happens for query "SELECT * FROM items : []": ER_NO_SUCH_TABLE: Table 'es_extended.items' doesn't exist`
`[zombieoutbreak] An error happens for query "SELECT * FROM weapons : []": ER_NO_SUCH_TABLE: Table 'es_extended.weapons' doesn't exist`

i followed every step from the installation page.

and when i try to join this comes: https://pastebin.com/76YaXzud

**Comment by Dislaik** [comment]
You are not following the installation
